### ISSUE TITLE
Document v1 and v2 in Wiki

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/MMFS#28]
It would be useful if the Wiki explained what v1 and v2 are about. 

I would send you a pull request, but it seems that GitHub doesn't support that for Wikis.

My initial suggestion is to add a new section to the Introuction page (some text below).

It would probably be helpful to do a more general update to the Wiki to explain V2. I am happy to attempt to do that if you can suggest a way for me to make edits.

--

Suggested text for Intoduction:

**MMFSv1 and MMFSv2**
MMFS is provided in two versions which differ in the way that floppy disc images are stored on the SD card.

In MMFSv1 there are many floppy disc images bundled into a single MMB file on an SD Card.

MMFSv2 is not intended as a replacement for MMFSv1, but rather supports a different mode of operation. In MMFSv2 floppy disc image files are stored directly on a FAT32 formatted SD Card without any MMB file.

In both versions of MMFS the individual disc images may be loaded into virtual drives for access from the BBC Micro using commands like *DIN explained in the Command Reference.

**Comment by hoglet67** [comment]
https://github.com/hoglet67/MMFS/wiki#mmfsv1-and-mmfsv2

**Comment by greenonline** [comment]
As the update suggested by @sharpie7 has been done, should this issue now be closed? 

However, as a total newcomer to this project, I was a little confused as to how the two versions of MMFS were intended to be used:

 - Can one use both at the same time, in the same ROM IC (and switch between the two)? 
 - Or, were two ROMs required? 
 - Could both ROMs be used at the same timeetc.)  

This may seem obvious to the initiated, but to a newcomer it isn't at all clear. 

After some searching around on google, I eventually found the most useful info in [this ebay item](https://www.ebay.co.uk/itm/265986688779)'s description:

> If you prefer MMFS2 on ROM please state at checkout otherwise will come with standard MMFS ROM
> - for a small extra fee I can also supply two ROMS, one with MMFS and the other with MMFS2 (only one can be used at once)

also

> Fits in both BBC Master and BBC Micro - microSD card can be changed when in situ on both - the only difference is a different ROM chip.

Therefore, asuming that I understand both of these quotes correctly, I would suggest appending to @sharpie7's text, something like this:

> Note: 
> - These are two *different* ROM images, and require burning to two different (E)(EP)ROM ICs. **Only one can be used at a time**. They can *not* be used together.
> - The Master and the Model B require different ROM images. A ROM for the Master can not be used in the Model B and vice versa.

Or something like that?

**Comment by hoglet67** [comment]
I've added a couple of bits of additional text to the wiki to try to make this a bit clearer:

In the [MMFSv1 and MMFSv2](https://github.com/hoglet67/MMFS/wiki/Home/_edit#mmfsv1-and-mmfsv2) section:

> While it is possible to have the MMFSv1 and MMFSv2 ROMs installed at the same time, it rarely makes sense to do this because they access disk images in different ways. So a disk image that is visible to MMFSv1 will not be visible to MMFSv2 (and visa versa). In addition, on a Model B you would need to use a ROM manager to make sure only one of them is active at a time, otherwise the default value of PAGE will be too high for most games. On a Master it's easier, because of better support in MOS 3.2 for multiple file systems.

In the [Configurations](https://github.com/hoglet67/MMFS/wiki/Home/_edit#configurations) section:

> There is a different MMFS ROM image for each of these hardware configurations, and the MMFS release .zip file includes all of them in a hierarchical folder structure. One of the challenges for someone getting started with MMFS is to select the image that most appropriate to their machine and the type of interface adapter. For more details on selecting the right ROM image, please refer to the [[Release Structure]] page.
