### ISSUE TITLE
SWMMFS3 ?

### ISSUE THREAD

**Issue by sharpie7** [hoglet67/MMFS#29]
Based on [this project](https://github.com/alanswx/BBCMicro_MiSTer). I am trying to do a BBC B with 1770 DFS and MMFS options.

Is there any reason why an SWMMFS3 can't be built and co-exist with DFS and a mouse with this address map:
FE60 - VIA with mouse
FE80 - FC1170 + control register
FEA0 - "user VIA" with SPI to SD card
?

What MMFS build options would you recommend for that configuration?

**Comment by hoglet67** [comment]
Copy top_SWMMFS2.asm to top_SWMMFS3.asm and change _VIA_BASE to &FEA0.

Then run the build.sh script.

Note, it's generally not recommended to have both MMFS and DFS fitted and active at the same time, as they both use they the file system number, so things get very confusing. This is done to maximise compatibility with games that check specifically that DFS is the current file system by testing the file system number.

You can build a version fo MMFS that uses a unique file system number by changing _EMUL_DFS to FALSE in the top_ file.

Dave

**Comment by sharpie7** [comment]
_Note, it's generally not recommended to have both MMFS and DFS fitted and active at the same time, as they both use they the file system number, so things get very confusing._

Thanks. That's a good tip. I might try another approach then!

**Comment by hoglet67** [comment]
The standard release package now includes this (MMFS/U3/SWMMFS.rom)
